app = 'spinnable-publer-mcp'
primary_region = 'fra'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '8000'
  TRANSPORT = 'sse'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    grace_period = '10s'
    interval = '30s'
    method = 'GET'
    path = '/health'
    timeout = '5s'

[vm]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[[vm.http_service.concurrency]]
  type = 'connections'
  hard_limit = 25
  soft_limit = 20

[[vm.http_service.concurrency]]
  type = 'requests'
  hard_limit = 100
  soft_limit = 80