# Fly.io deployment configuration for Publer MCP
# Following Spinnable MCP Playbook standards

app = 'publer_mcp'
primary_region = 'cdg'

[build]

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.checks]
    [http_service.checks.health]
      grace_period = "5s"
      interval = "15s"
      method = "GET"
      timeout = "10s"
      path = "/health"

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[deploy]
  strategy = 'rolling'